# Generated by Django 4.2.3 on 2023-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_recoginition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceembedding",
            name="embedding",
            field=models.CharField(max_length=2555),
        ),
    ]
